package org.batoo.jpa.community.test.i167;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Version;

@SuppressWarnings("javadoc")
@Entity
public class EntityWithVersionAndAutogeneratedValueId {
	@Id
	@Column(name = "ID", nullable = false)
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	private final Long id = null;

	@Column(nullable = false)
	private Long value = null;

	@Version
	@Column(nullable = false)
	private final Long timeStamp = null;

	public EntityWithVersionAndAutogeneratedValueId() {
		super();
	}

	public EntityWithVersionAndAutogeneratedValueId(Long value) {
		this.value = value;
	}

	public Long getId() {
		return this.id;
	}

	public Long getTimeStamp() {
		return this.timeStamp;
	}

	public Long getValue() {
		return this.value;
	}

	public void setValue(Long value) {
		this.value = value;
	}

}
