package org.batoo.jpa.community.test.i167;

import org.batoo.jpa.community.test.BaseCoreTest;
import org.batoo.jpa.community.test.NoDatasource;
import org.junit.Test;

public class TestI167 extends BaseCoreTest {
	@Test
	@NoDatasource
	public void test(){
		EntityWithVersionAndAutogeneratedValueId entity = new EntityWithVersionAndAutogeneratedValueId();
		persist(entity);
		this.commit();
	}
}
