CREATE TABLE ITEM (ID INT NOT NULL, name VARCHAR(128), PRIMARY KEY ( ID ) );
CREATE TABLE CATEGORY (ID INT NOT NULL, name VARCHAR(128), PRIMARY KEY ( ID ) );
CREATE TABLE ITEM_CATEGORY (ITEM_ID INT NOT NULL, CATEGORY_ID INT NOT NULL, PRIMARY KEY ( ITEM_ID, CATEGORY_ID ) );

